GET http://localhost:3001/cardVault

###

Get http://localhost:3001/cardVault/61048488839c1debd0b8654

###

POST http://localhost:3001/cardVault
Content-Type: application/json

{
  "name": "sorren",
  "color": "black"
}

###

DELETE http://localhost:3001/cardVault/


###
PATCH http://localhost:3001/cardVault/