GET http://localhost:3001/cardVault

###

Get http://localhost:3001/cardVault

###

POST http://localhost:3001/cardVault
Content-Type: application/json

{
  "name": "sorren",
  "color": "black"
}

###

DELETE http://localhost:3001/cardVault/610590d00f4c4b2c4e8b966b


###
PATCH http://localhost:3001/cardVault/610599855d1a5b28163288b1
Content-Type: application/json

{
  "name": "test",
  "color": "blue"

}